"""AMD-only extra native qualification for exact extracted synthetic flow DUTs.

Read an already-passed three-flow result. Reuse the actual official extractor,
then call the unchanged checker/oracle for just the two exact generated byte
sequences. Original flow/native evidence is only read. No new model calls,
worker replay, FIFO or executor are implemented here.
"""
import hashlib
import importlib.util
import json
from pathlib import Path
import re
import sys
from unittest.mock import patch
import urllib.request

import lemmings_feedback as feedback

HERE = Path(__file__).resolve().parent
CORE_MANIFEST_SHA = 'b5608f4d48e68a8c6f1fb40119226dd0685ade946abcdb29ef1e45fa7ae852ad'
CHECKER_SHA = 'e178d62a61bd279bb3dfcf4a17357a90e8a26b4537da83ba0f6e3714ae0a753a'
OFFICIAL_BASELINE_SHA = '537783e39db22079c33c19af475dbdb760a29ff1656a48c481d434131f84fb51'


def sha(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def read(path):
    return json.loads(Path(path).read_text(encoding='utf-8'))


def save(path, data):
    with Path(path).open('x', encoding='utf-8') as stream:
        json.dump(data, stream, ensure_ascii=False, indent=2)
        stream.write('\n')


def load(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def no_network(*args, **kwargs):
    raise RuntimeError('exact synthetic DUT qualification makes no model/network requests')


def safe_file(path, root):
    path = Path(path)
    if path.is_symlink() or not path.is_file() or not path.resolve().is_relative_to(root):
        raise RuntimeError('unexpected source/evidence path: ' + str(path))
    return path.resolve()


def qualify(paired, root, out, pure_flow_result, pure_flow_result_sha256,
            original_packet_root, before_case=None):
    """Two cases, at most six existing native stages; source freezes are external.

    The owner's stage must validate its current SOURCE_MANIFEST and resource
    guard, install the original bounded paired.owned_command, reserve six x60
    seconds plus cleanup, and preserve all receipts. before_case is that
    existing budget/freeze callback, not an alternate execution mechanism.
    """
    if sys.platform != 'linux' or not sys.dont_write_bytecode:
        raise RuntimeError('only authorized AMD Python -B may execute this extension')
    root, out, original_packet_root = (Path(x).resolve() for x in (root, out, original_packet_root))
    if root != Path(feedback.__file__).resolve().parent or out == root or not out.is_relative_to(root):
        raise RuntimeError('extension must use the owner\'s separate frozen packet/output')
    if out.exists():
        raise RuntimeError('never rerun or replace an existing exact-DUT qualification')
    if sha(feedback.__file__) != CHECKER_SHA or sha(root / 'IMPLEMENTATION_MANIFEST.json') != CORE_MANIFEST_SHA:
        raise RuntimeError('checker/core source does not match this reviewed extension')
    for name, metadata in read(root / 'IMPLEMENTATION_MANIFEST.json')['files'].items():
        if Path(name).is_absolute() or '..' in Path(name).parts:
            raise RuntimeError('unsafe core source member')
        if sha(safe_file(root / name, root)) != metadata['sha256']:
            raise RuntimeError('frozen core member changed: ' + name)
    official_path = safe_file(root / 'package/baseline.py', root)
    if sha(official_path) != OFFICIAL_BASELINE_SHA:
        raise RuntimeError('official extractor source changed')
    original_manifest_path = safe_file(original_packet_root / 'SOURCE_MANIFEST.json', original_packet_root)
    pure_path = safe_file(pure_flow_result, original_packet_root)
    if sha(pure_path) != pure_flow_result_sha256:
        raise RuntimeError('pure/flow original receipt changed')
    result = read(pure_path)
    if (result.get('complete') is not True or result.get('passed') is not True or result.get('error') is not None or
            result.get('real_model_calls') != 0 or result.get('real_eda_commands') != 0 or
            result.get('implementation_manifest_sha256') != CORE_MANIFEST_SHA or
            result.get('source_manifest_sha256') != sha(original_manifest_path)):
        raise RuntimeError('original pure/flow qualification is not confirmed')
    original_sources = read(original_manifest_path)
    # Preserve and verify every byte of the prior packet, not only its filename.
    for name, digest in original_sources.items():
        if Path(name).is_absolute() or '..' in Path(name).parts:
            raise RuntimeError('unsafe original source manifest member')
        if sha(safe_file(original_packet_root / name, original_packet_root)) != digest:
            raise RuntimeError('original packet changed: ' + name)
    expected_fixed = result['fixed_control_source_hashes']
    for name in ('lemmings_feedback.py', 'controls.py', 'test_lemmings_feedback.py',
                 'flow_controls.py', 'pure_flow_stage.py', 'baseline_worker.py',
                 'flow_fixtures/good_entry1.sv', 'flow_fixtures/bad_right_double_bump.sv'):
        if original_sources[name] != expected_fixed[name]:
            raise RuntimeError('prior flow source binding differs: ' + name)
    if original_sources['package/baseline.py'] != OFFICIAL_BASELINE_SHA:
        raise RuntimeError('prior flow did not use this official extractor')
    old_flow = safe_file(pure_path.parent / 'flow_results/FLOW_RESULT.json', original_packet_root)
    if read(old_flow) != result['reports']['flow']:
        raise RuntimeError('saved flow result differs from the qualified parent receipt')
    prior = result['reports']['flow']
    if (prior.get('passed') is not True or prior.get('simulated') is not True or
            prior.get('actual_model_calls') != 0 or prior.get('actual_eda_calls') != 0 or
            prior.get('first_C_P_request_identical') is not True or prior.get('simulated_http_calls') != 4):
        raise RuntimeError('three-flow qualification incomplete')
    solve = old_flow.parent / 'flow/candidate_repairs_once'
    requests_path = safe_file(solve / 'requests.json', original_packet_root)
    requests = read(requests_path)
    if len(requests) != 2:
        raise RuntimeError('expected the exact original simulated bad-to-good two-request flow')
    source_prompt = safe_file(solve / 'prompt_only/prompt.txt', original_packet_root)
    prompt = source_prompt.read_text(encoding='utf-8')
    parsed = feedback.parse(prompt)
    if parsed is None:
        raise RuntimeError('retained complete prompt is unsupported by the frozen checker')
    plan_path = HERE / 'EXACT_DUT_CASES.json'
    plan = read(plan_path)
    if plan['schema'] != 'lemmings_exact_flow_dut_native_extension_v1' or len(plan['cases']) != 2:
        raise RuntimeError('wrong exact-DUT extension plan')
    if plan['official_extractor_sha256'] != OFFICIAL_BASELINE_SHA or plan['core_manifest_sha256'] != CORE_MANIFEST_SHA:
        raise RuntimeError('extension source lineage differs')
    original_evidence = {str(p): sha(p) for p in (pure_path, original_manifest_path, old_flow, requests_path, source_prompt)}
    out.mkdir(parents=True, exist_ok=False)
    save(out / 'EXACT_DUT_INTENT.json', dict(schema=plan['schema'], artificial_qualification_only=True,
         real_model_max=0, extra_native_cases=2, extra_eda_max=6, eda_cap_seconds=60,
         recommended_stage_cap_seconds=450, retries=0, original_worker_rerun=False,
         original_native_cases_rerun=False, core_manifest_sha256=CORE_MANIFEST_SHA,
         official_extractor_sha256=OFFICIAL_BASELINE_SHA, plan_sha256=sha(plan_path),
         original_evidence_sha256=original_evidence))
    records = []
    with patch.object(urllib.request, 'urlopen', no_network):
        official = load('lemmings_exact_native_official_extract', official_path)
        for case in plan['cases']:
            if before_case is not None:
                before_case(case)
            attempt = case['original_flow_attempt']
            response_path = safe_file(solve / 'requests' / str(attempt) / 'response.json', original_packet_root)
            request_path = safe_file(solve / 'requests' / str(attempt) / 'request.json', original_packet_root)
            flow_input = safe_file(solve / ('lemmings_check_' + str(attempt)) / 'input.sv', original_packet_root)
            fixture_raw = safe_file(original_packet_root / case['flow_fixture'], original_packet_root)
            if sha(fixture_raw) != case['flow_fixture_sha256']:
                raise RuntimeError('wrong frozen artificial flow fixture')
            if (sha(response_path) != requests[attempt]['response_sha256'] or
                    sha(request_path) != requests[attempt]['request_sha256'] or
                    requests[attempt].get('response_received') is not True):
                raise RuntimeError('retained simulated request/response receipt mismatch')
            response = read(response_path)
            reply = response['choices'][0]['message'].get('content') or ''
            code = official.extract(reply, 'rtl')
            fixture_extracted = official.extract(fixture_raw.read_text(encoding='utf-8'), 'rtl')
            if (code != fixture_extracted or code.encode('utf-8') != flow_input.read_bytes() or
                    len(re.findall(r'(?m)^\s*module\s+TopModule\b', code)) != 1 or
                    len(re.findall(r'(?m)^\s*module\s+', code)) != 1):
                raise RuntimeError('exact official extraction / flow DUT binding failed')
            if sha(flow_input) != case['expected_extracted_dut_sha256']:
                raise RuntimeError('actual official extractor bytes differ from the statically prepared expectation')
            case_dir = out / case['name']
            case_dir.mkdir()
            # Actual canonical fixture is written from the real official API
            # output only on AMD. No static extraction emulation authorizes it.
            canonical = case_dir / 'official_extracted_fixture.sv'
            canonical.write_text(code, encoding='utf-8', newline='\n')
            if canonical.read_bytes() != flow_input.read_bytes():
                raise RuntimeError('native qualification source is not byte-identical to prior flow source')
            evidence = {str(p): sha(p) for p in (response_path, request_path, flow_input, fixture_raw)}
            original_evidence.update(evidence)
            save(case_dir / 'EXTRACTION_RECEIPT.json', dict(
                schema='official_extractor_to_exact_synthetic_dut_v1',
                actual_execution_required=True, executed_on_amd=True,
                synthetic_model_response=True, model_generated_competition_design=False,
                official_extractor_path=str(official_path), official_extractor_sha256=sha(official_path),
                original_flow_attempt=attempt, original_evidence_sha256=evidence,
                exact_dut_sha256=sha(canonical), exact_dut_bytes=canonical.stat().st_size,
                official_extracted_fixture=str(canonical), flow_input=str(flow_input),
                flow_response=str(response_path), equality='UTF8_bytes_exact_no_comment_or_semantic_equivalence'))
            text = feedback.check(prompt, code, case_dir / 'native', 0, paired, 'SyntheticLemmings', root)
            check = case_dir / 'native/lemmings_check_0'
            adapter = read(check / 'probe/adapter_receipt.json')
            native_input, native_dut = check / 'input.sv', check / 'probe/dut.sv'
            if native_input.read_bytes() != canonical.read_bytes() or native_dut.read_bytes() != canonical.read_bytes():
                raise RuntimeError('native source copy lost exact official extraction binding')
            if case['expected'] == 'pass':
                if text != '' or adapter['status'] != 'pass' or adapter['mismatches'] != 0:
                    raise RuntimeError('exact extracted positive did not pass')
            else:
                if not text or adapter['status'] != 'fail' or adapter['failure_kind'] != 'semantic_mismatch':
                    raise RuntimeError('exact extracted negative not semantically detected')
                point = read(check / 'counterexample.json')
                if feedback.feedback_text(point) != text:
                    raise RuntimeError('native counterexample feedback mismatch')
                old_feedback = safe_file(solve / ('lemmings_check_' + str(attempt)) / 'feedback.txt', original_packet_root)
                old_point = safe_file(solve / ('lemmings_check_' + str(attempt)) / 'counterexample.json', original_packet_root)
                next_request = safe_file(solve / 'requests' / str(attempt + 1) / 'request.json', original_packet_root)
                if (old_feedback.read_text(encoding='utf-8') != text or read(old_point) != point or
                        read(next_request)['messages'][1]['content'] !=
                        prompt + '\nPrevious candidate:\n' + code + '\nCandidate diagnostics:\n' + text):
                    raise RuntimeError('actual native first counterexample is not the exact feedback consumed by retained flow')
                original_evidence.update({str(p): sha(p) for p in (old_feedback, old_point, next_request)})
            native_files = ['input.sv', 'contract.json', 'trace_binding.json', 'probe/adapter_receipt.json',
                            'probe/result.json', 'probe/dut.sv', 'probe/tb.sv',
                            'probe/xvlog.log', 'probe/xelab.log', 'probe/xsim.log']
            if case['expected'] != 'pass':
                native_files += ['counterexample.json', 'feedback.txt']
            record = dict(name=case['name'], expected=case['expected'], passed=True,
                native_check=str(check), original_flow_attempt=attempt,
                original_flow_solve=str(solve), original_flow_response=str(response_path),
                original_flow_input=str(flow_input), original_response_sha256=sha(response_path),
                exact_dut_sha256=sha(canonical), original_flow_input_sha256=sha(flow_input),
                native_input_sha256=sha(native_input), native_dut_sha256=sha(native_dut),
                extractor_receipt=str(case_dir / 'EXTRACTION_RECEIPT.json'),
                extractor_receipt_sha256=sha(case_dir / 'EXTRACTION_RECEIPT.json'),
                native_evidence_sha256={name: sha(check / name) for name in native_files},
                actual_native_stages=len(adapter['stages']), synthetic_source=True,
                retained_flow_feedback_equal_to_native=(case['expected'] != 'pass'),
                reused_core_native_evidence=False, actual_model_calls=0)
            save(case_dir / 'EXACT_DUT_CASE_RESULT.json', record)
            records.append(record)
    for path, digest in original_evidence.items():
        if sha(path) != digest:
            raise RuntimeError('original evidence changed during exact-DUT extension')
    if sha(official_path) != OFFICIAL_BASELINE_SHA or sha(feedback.__file__) != CHECKER_SHA:
        raise RuntimeError('extractor/checker source changed')
    summary = dict(schema='lemmings_exact_flow_dut_native_extension_result_v1',
        complete=True, passed=True, actual_model_calls=0,
        actual_eda_commands=sum(x['actual_native_stages'] for x in records),
        extra_cases=2, original_worker_reexecuted=False, original_21_native_reexecuted=False,
        core_manifest_sha256=CORE_MANIFEST_SHA, official_extractor_sha256=OFFICIAL_BASELINE_SHA,
        pure_flow_result_sha256=pure_flow_result_sha256, original_sources_unchanged=True,
        records=records, original_evidence_sha256=original_evidence,
        scope='synthetic exact-DUT binding qualification only; no real model score or generation evidence')
    if summary['actual_eda_commands'] != 6:
        raise RuntimeError('expected exactly six additional native stages')
    save(out / 'EXACT_DUT_EXTENSION_RESULT.json', summary)
    save(out / 'BINDING_INPUTS.json', dict(schema='synthetic_exact_dut_binding_inputs_v1',
        qualified=True, result_sha256=sha(out / 'EXACT_DUT_EXTENSION_RESULT.json'),
        actual_model_calls=0, cases=records,
        required_binder_rule='model reply official-extract bytes == exact_dut_sha256 == native input/dut bytes; never waive equality'))
    return summary
